#!/bin/bash
# Authors: MDL and TŠ
# Scripts processing clustering results of mmseqs, c-values [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
# Example for Scer_2020 species

#SBATCH --job-name=numcluster_hs
#SBATCH --output=numcluster_hs_out.txt
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=100:00:00
#SBATCH --mem 20000


echo "Starting experiment!!!"

c_start=0
c_end=0.8

#./mmseqs_cluster_2022/results_0_8/db_clu_all.tsv

for c in $(seq $c_start 0.1 $c_end)
do
	echo "Starting experiment for c value: $c"
	path=PATH_TO_ANALYSIS_FOLDER/results_${c/./_}/
	echo ${path}
	
	rm -rf ${path}Hsap/dbAllPlus_clu_${c/./_}_Hsap_out_EXT.txt
	cat allLCA_n_667.txt >> ${path}Hsap/dbAllPlus_clu_${c/./_}_Hsap_out_EXT.txt
	cat ${path}Hsap/dbAllPlus_clu_${c/./_}_Hsap_out.txt >> ${path}Hsap/dbAllPlus_clu_${c/./_}_Hsap_out_EXT.txt		
	time awk -v t=9606 -v P=39 -f getGL_HS.awk ${path}Hsap/dbAllPlus_clu_${c/./_}_Hsap_out_EXT.txt > ${path}Hsap/res_dbAllPlus_clu_${c/./_}_Hsap_out_EXT.txt
	awk '{if ($0 ~ /Total/) {cnt = 1; print} else if (cnt >= 1 && cnt <= 39){ cnt++; print}}' ${path}Hsap/res_dbAllPlus_clu_${c/./_}_Hsap_out_EXT.txt > ${path}Hsap/gain_loss_${c/./_}_Hsap.txt

	rm -rf ${path}Hsap/dbAllPlus_clu_${c/./_}_Hsap_out_EXT.txt
	
done

echo "Experiment done"
