#!/bin/bash
# Authors: MDL and TŠ  
# Scripts processing clustering results of mmseqs, c-values [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

#SBATCH --job-name=numcluster_dmel
#SBATCH --output=numcluster_dmel_out.txt
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=100:00:00
#SBATCH --mem 20000


echo "Starting experiment!!!"

c_start=0
c_end=0.8

#./mmseqs_cluster_2022/results_0_8/db_clu_all.tsv

for c in $(seq $c_start 0.1 $c_end)
do
	echo "Starting experiment for c value: $c"
	path=PATH_TO_ANALYSIS_FOLDER/results_${c/./_}/
	echo ${path}

	rm ${path}Dmel/dbAllPlus_clu_${c/./_}_Dmel_out_EXT.txt
	cat allLCA_n_667.txt >> ${path}Dmel/dbAllPlus_clu_${c/./_}_Dmel_out_EXT.txt
	cat ${path}Dmel/dbAllPlus_clu_${c/./_}_Dmel_out.txt >> ${path}Dmel/dbAllPlus_clu_${c/./_}_Dmel_out_EXT.txt		
	time awk -v t=7227 -v P=31 -f getGL_Dmel.awk ${path}Dmel/dbAllPlus_clu_${c/./_}_Dmel_out_EXT.txt > ${path}Dmel/res_dbAllPlus_clu_${c/./_}_Dmel_out_EXT.txt
	awk '{if ($0 ~ /Total/) {cnt = 1; print} else if (cnt >= 1 && cnt <= 31){ cnt++; print}}' ${path}Dmel/res_dbAllPlus_clu_${c/./_}_Dmel_out_EXT.txt > ${path}Dmel/gain_loss_${c/./_}_Dmel.txt
	rm ${path}Dmel/dbAllPlus_clu_${c/./_}_Dmel_out_EXT.txt
done

echo "Experiment done"
