#!/bin/bash
# Authors: MDL and TŠ
# Scripts processing clustering results of mmseqs, c-values [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
# Example for Scer_2020 species

#SBATCH --job-name=numcluster_scer
#SBATCH --output=numcluster_scer_out.txt
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=100:00:00
#SBATCH --mem 20000


echo "Starting experiment!!!"

c_start=0
c_end=0.8

#./mmseqs_cluster_2022/results_0_8/db_clu_all.tsv

for c in $(seq $c_start 0.1 $c_end)
do
	echo "Starting experiment for c value: $c"
	path=PATH_TO_ANALYSIS_FOLDER/results_${c/./_}/
	echo ${path}
	
	rm ${path}Scer/dbAllPlus_clu_${c/./_}_Scer_out_EXT.txt
	cat allLCA_n_667.txt >> ${path}Scer/dbAllPlus_clu_${c/./_}_Scer_out_EXT.txt
	cat ${path}Scer/dbAllPlus_clu_${c/./_}_Scer_out.txt >> ${path}Scer/dbAllPlus_clu_${c/./_}_Scer_out_EXT.txt		
	time awk -v t=559292 -v P=28 -f getGL_Scer.awk ${path}Scer/dbAllPlus_clu_${c/./_}_Scer_out_EXT.txt > ${path}Scer/res_dbAllPlus_clu_${c/./_}_Scer_out_EXT.txt
	awk '{if ($0 ~ /Total/) {cnt = 1; print} else if (cnt >= 1 && cnt <= 28){ cnt++; print}}' ${path}Scer/res_dbAllPlus_clu_${c/./_}_Scer_out_EXT.txt > ${path}Scer/gain_loss_${c/./_}_Scer.txt
	rm ${path}Scer/dbAllPlus_clu_${c/./_}_Scer_out_EXT.txt
done

echo "Experiment done"
