#!/bin/bash
# Authors: TŠ and MDL
# Scripts submits mmseqs2 clustering with c-values [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

#SBATCH --job-name=mmseqs
#SBATCH --output=mmseqs_All_c_0_0_8_out.txt
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --time=100:00:00
#SBATCH --mem 20000


echo "Starting experiment."

c_start=0
c_end=0.8

mkdir tmp
mmseqs createdb ./DB/all_db.fasta db_all
rm -rf tmp

for c in $(seq $c_start 0.1 $c_end)
do
	echo "Starting experiment for c value: $c"
	path=./results_${c/./_}/
	mkdir ${path}
	echo ${path}

	mkdir tmp
	mkdir results_tmp

	# cluster
	time mmseqs cluster db_all ./results_tmp/db_clu_all tmp -e 0.001 -c ${c} --max-seqs 400 --cluster-mode 1 --threads 24
	# generate tsv cluster file from cluster database
	time mmseqs createtsv db_all db_all ./results_tmp/db_clu_all ./results_tmp/db_clu_all.tsv --threads 24

	cp results_tmp/db_clu_all.tsv ${path}

	rm -rf tmp
	rm -rf results_tmp

done

echo "Experiment done."
